// SPDX-License-Identifier: MIT
// FILE: test/FUZZ_MLDSA44.t.sol
//
// DIFFERENTIAL + MUTATION CAMPAIGN against both in-tree ML-DSA-44 EVM
// verifiers: the reference implementation test/ZZZ_E2ERef.sol and the shipped
// src/MLDSA44Verifier.sol.
//
// 2180 cases, every one of them fed to BOTH verifiers (4360 verifications).
// The corpus is generated by tools/fixtures/fuzz_build.py and each case is
// oracle-checked against the pythonref FIPS-204 implementation BEFORE it is
// emitted, so every assertion below is a genuine differential test (EVM
// verdict == python reference verdict), and any divergence between the two
// implementations is caught as well.  A revert counts as non-acceptance
// (staticcall-wrapped).
//
// Battery A — "fs_*" shards, 800 must-ACCEPT cases:
//   40 fresh keys x 20 message lengths
//   {0,1,2,31,32,33,63,64,65,69,70,71,135,136,137,206,272,342,500,8192}.
//   The lengths straddle the SHAKE256 rate (136 B) for the raw message and
//   for the mu pre-image 66+|M| at exact block boundaries (|M| = 70 -> 136,
//   206 -> 272, 342 -> 408), plus the empty message and an 8 KiB message
//   (the ACVP maximum).
//
// Battery B — "fm_*" shards, 1380 must-REJECT cases: 60 base signatures
//   x 23 systematic sigma mutations:
//     flip.ctilde / flip.z / flip.h  single random bit flip per region
//     flip.multi3                    three random bit flips anywhere
//     z.plus1                        one z coefficient incremented
//     z.boundary.g1mb                one z coefficient forced to exactly
//                                    |z| = gamma1 - beta = 130994, which strict
//                                    FIPS 204 requires to be REJECTED
//     z.inrange.g1mb1                one z coefficient forced to
//                                    |z| = gamma1 - beta - 1 = 130993, i.e.
//                                    inside the norm bound, so it must be
//                                    rejected by the commitment hash instead
//     z.gamma1 / z.maxfield          z coefficient at gamma1 / -(gamma1-1)
//     z.rowswap                      two whole z rows exchanged
//     h.count.gt.omega               cumulative hint count 81 > omega = 80
//     h.nonmonotone.idx              decreasing indices inside one polynomial
//     h.nonmonotone.cnt              decreasing cumulative counts
//     h.nonzero.pad                  non-zero byte in the hint padding region
//     h.allzero                      structurally valid, empty hint vector
//     sig.trunc2419 / sig.ext2421 / sig.empty      length mutations
//     sig.random                     2420 fully random bytes
//     msg.swap                       signature vs a different message
//     pk.swap                        signature vs a different public key
//     ctilde.zero / ctilde.other     zeroed / foreign commitment
//   The h.* classes exercise the FIPS 204 HintBitUnpack (Algorithm 21)
//   validity conditions on the hEncode(h) region of the 2420-byte signature.
//   (An h index >= 256 is structurally unreachable: FIPS 204 encodes hint
//    positions as single bytes, so no decoder can ever see one.)
//
// REGENERATE FIXTURES:
//   pythonref/myenv/bin/python tools/fixtures/fuzz_build.py --build
pragma solidity ^0.8.25;

import {Test, console} from "forge-std/Test.sol";
import {_F1600_AT, _F1600_CODE} from "./ZZZ_FastKeccak.sol";
import {deployF1600_170} from "./ZZZ_FastKeccak170.sol";
import {ZZZ_E2ERef, E2E_PK_SIZE} from "./ZZZ_E2ERef.sol";
import {MLDSA44Verifier} from "../src/MLDSA44Verifier.sol";

contract FuzzMLDSA44Test is Test {
    /// field order matches SHARD_T in tools/fixtures/fuzz_build.py
    struct Shard {
        bytes[] pkBlobs; // deduplicated 20,544-byte pk payloads
        uint256[] pkIdx; // case -> pk index
        bytes[] msgs;
        bytes[] sigs;
        bool[] expect; //   python-oracle verdict
        string[] labels;
    }

    /// in-repo shard builder (see tools/fixtures/README_shards.md); vm.ffi
    /// runs with cwd = the repository root, so the path is repo-relative.
    string constant FX = "tools/fixtures/fuzz_build.py";

    ZZZ_E2ERef refVerifier;
    MLDSA44Verifier shipped;
    uint256 private _pkNonce;

    function setUp() public {
        vm.etch(_F1600_AT, _F1600_CODE);
        refVerifier = new ZZZ_E2ERef();
        shipped = new MLDSA44Verifier(deployF1600_170());
    }

    // ------------------------------------------------------------------ utils

    /// The builder prints the requested shard as hex on stdout (vm.ffi decodes
    /// hex automatically) and caches it under test/fixtures/, so the corpus is
    /// generated once and every later run is a plain file read.
    function _read(string memory name) internal returns (bytes memory out) {
        string[] memory c = new string[](3);
        c[0] = "pythonref/myenv/bin/python";
        c[1] = FX;
        c[2] = name;
        out = vm.ffi(c);
        require(out.length > 64, "empty fixture shard");
    }

    /// place the raw reference-layout pk payload as account code (see the
    /// EIP-3541 note in test/ACVP_MLDSA44.t.sol: CREATE cannot deploy blobs
    /// whose first byte, i.e. tr[0], is 0xEF — ~1/256 of the keys)
    function _placeRefPk(bytes memory blob) internal returns (address a) {
        a = address(uint160(uint256(keccak256(abi.encodePacked("fuzz.pk.slot", ++_pkNonce)))));
        vm.etch(a, blob);
    }

    /// the shipped verifier's pk data contract: 0x00 || payload, deployed with
    /// a plain CREATE (always possible thanks to the 0x00 prefix)
    function _deployShippedPk(bytes memory blob) internal returns (address ptr) {
        bytes memory data = bytes.concat(hex"00", blob);
        bytes memory initCode = abi.encodePacked(
            bytes1(0x61), uint16(data.length), hex"600e600039", bytes1(0x61), uint16(data.length), hex"6000f3", data
        );
        assembly ("memory-safe") {
            ptr := create(0, add(initCode, 32), mload(initCode))
        }
        require(ptr != address(0), "pk data contract deploy failed");
    }

    function _acceptRef(address pk, bytes memory m, bytes memory sig) internal view returns (bool accepted) {
        (bool ok, bytes memory ret) = address(refVerifier).staticcall(abi.encodeCall(ZZZ_E2ERef.verify, (pk, m, sig)));
        accepted = ok && ret.length == 32 && abi.decode(ret, (bool));
    }

    function _acceptShipped(address pk, bytes memory m, bytes memory sig) internal view returns (bool accepted) {
        (bool ok, bytes memory ret) =
            address(shipped).staticcall(abi.encodeCall(MLDSA44Verifier.verify, (pk, m, sig)));
        accepted = ok && ret.length == 32 && abi.decode(ret, (bool));
    }

    // ------------------------------------------------------------ shard runner

    function _run(string memory prefix, uint256 k) internal {
        Shard memory s = abi.decode(_read(string.concat(prefix, "_", vm.toString(k), ".hex")), (Shard));
        uint256 nk = s.pkBlobs.length;
        address[] memory refPk = new address[](nk);
        address[] memory shipPk = new address[](nk);
        for (uint256 i = 0; i < nk; ++i) {
            assertEq(s.pkBlobs[i].length, E2E_PK_SIZE, "pk blob size");
            refPk[i] = _placeRefPk(s.pkBlobs[i]);
            shipPk[i] = _deployShippedPk(s.pkBlobs[i]);
        }

        uint256 n = s.sigs.length;
        uint256 accR;
        uint256 accS;
        for (uint256 i = 0; i < n; ++i) {
            uint256 p = s.pkIdx[i];
            bool gotRef = _acceptRef(refPk[p], s.msgs[i], s.sigs[i]);
            bool gotShip = _acceptShipped(shipPk[p], s.msgs[i], s.sigs[i]);
            if (gotRef != s.expect[i] || gotShip != s.expect[i]) {
                console.log("FUZZ MISMATCH:", s.labels[i]);
                console.log("  expected / reference / shipped:", s.expect[i], gotRef, gotShip);
            }
            assertEq(gotRef, s.expect[i], s.labels[i]);
            assertEq(gotShip, s.expect[i], s.labels[i]);
            if (gotRef) ++accR;
            if (gotShip) ++accS;
        }
        console.log("shard cases / reference-accepted / shipped-accepted:", n, accR, accS);
    }

    // ------------------------------- battery A: valid signatures (800)

    function test_fuzz_sigs_shard0() public {
        _run("fs", 0);
    }

    function test_fuzz_sigs_shard1() public {
        _run("fs", 1);
    }

    function test_fuzz_sigs_shard2() public {
        _run("fs", 2);
    }

    function test_fuzz_sigs_shard3() public {
        _run("fs", 3);
    }

    function test_fuzz_sigs_shard4() public {
        _run("fs", 4);
    }

    function test_fuzz_sigs_shard5() public {
        _run("fs", 5);
    }

    function test_fuzz_sigs_shard6() public {
        _run("fs", 6);
    }

    function test_fuzz_sigs_shard7() public {
        _run("fs", 7);
    }

    function test_fuzz_sigs_shard8() public {
        _run("fs", 8);
    }

    function test_fuzz_sigs_shard9() public {
        _run("fs", 9);
    }

    function test_fuzz_sigs_shard10() public {
        _run("fs", 10);
    }

    function test_fuzz_sigs_shard11() public {
        _run("fs", 11);
    }

    function test_fuzz_sigs_shard12() public {
        _run("fs", 12);
    }

    // ------------------------------- battery B: mutated sigmas (1380)

    function test_fuzz_mut_shard0() public {
        _run("fm", 0);
    }

    function test_fuzz_mut_shard1() public {
        _run("fm", 1);
    }

    function test_fuzz_mut_shard2() public {
        _run("fm", 2);
    }

    function test_fuzz_mut_shard3() public {
        _run("fm", 3);
    }

    function test_fuzz_mut_shard4() public {
        _run("fm", 4);
    }

    function test_fuzz_mut_shard5() public {
        _run("fm", 5);
    }

    function test_fuzz_mut_shard6() public {
        _run("fm", 6);
    }

    function test_fuzz_mut_shard7() public {
        _run("fm", 7);
    }

    function test_fuzz_mut_shard8() public {
        _run("fm", 8);
    }

    function test_fuzz_mut_shard9() public {
        _run("fm", 9);
    }

    function test_fuzz_mut_shard10() public {
        _run("fm", 10);
    }

    function test_fuzz_mut_shard11() public {
        _run("fm", 11);
    }

    function test_fuzz_mut_shard12() public {
        _run("fm", 12);
    }

    function test_fuzz_mut_shard13() public {
        _run("fm", 13);
    }

    function test_fuzz_mut_shard14() public {
        _run("fm", 14);
    }

    function test_fuzz_mut_shard15() public {
        _run("fm", 15);
    }

    function test_fuzz_mut_shard16() public {
        _run("fm", 16);
    }

    function test_fuzz_mut_shard17() public {
        _run("fm", 17);
    }

    function test_fuzz_mut_shard18() public {
        _run("fm", 18);
    }

    function test_fuzz_mut_shard19() public {
        _run("fm", 19);
    }

    function test_fuzz_mut_shard20() public {
        _run("fm", 20);
    }

    function test_fuzz_mut_shard21() public {
        _run("fm", 21);
    }

    function test_fuzz_mut_shard22() public {
        _run("fm", 22);
    }
}
