// SPDX-License-Identifier: MIT
// FILE: test/KAT_MLDSA44.t.sol
// FOR SECURITY RESEARCH ONLY — NOT FOR PRODUCTION USE
//
// THE 100-KEY KAT BREADTH SUITE, against both in-tree verifiers: the reference
// implementation test/ZZZ_E2ERef.sol and the shipped src/MLDSA44Verifier.sol.
//
// Corpus: every one of the 100 records of
// pythonref/assets/PQCsignKAT_Dilithium2.rsp — 100 DISTINCT public keys, 100
// distinct messages, all must-accept. Exactly ONE of those 100 records is read
// anywhere else in the tree (count 0, and only for its `mlen` field, by
// tools/fixtures/vecgen.py), so this suite is the only thing that verifies the
// other 99 keys.
//
// WHAT THIS CORPUS IS — the same caveat the builder carries, because it is the
// thing an auditor will want to check:
//
//   * NOT a NIST artefact, and NO NIST authority. The file is in the NIST PQC
//     KAT format and its seeds and messages ARE the ones the NIST KAT harness
//     emits — `AES256_CTR_DRBG(bytes(range(48)))` — which the builder replays
//     and asserts byte-for-byte. The keys and signatures were generated by
//     pythonref/dilithium_py under FIPS 204 ML-DSA-44. (The upstream
//     dilithium-py file of the same name holds NIST PQC Round 3 Dilithium2
//     vectors and does not match this one; see
//     pythonref/assets/provenance.txt.)
//   * What it buys is BREADTH: 100 independent third-party key/message pairs
//     accepted by both EVM verifiers, in the same evidential class as the
//     `fs_*` fuzz battery. The official-answer coverage is in
//     test/ACVP_MLDSA44.t.sol (`ah_*`, `at_*`) and test/FV2_AcvpKeyGen.t.sol.
//
// Every expected verdict is reproduced by the pythonref oracle at build time
// before it is emitted, and the builder aborts if any record fails to replay
// from the DRBG, if the 100 keys are not pairwise distinct, or if any of them
// also occurs in the ACVP corpora.
//
// REGENERATE FIXTURES:
//   pythonref/myenv/bin/python tools/fixtures/kat_build.py --build
pragma solidity ^0.8.25;

import {Test, console} from "forge-std/Test.sol";
import {_F1600_AT, _F1600_CODE} from "./ZZZ_FastKeccak.sol";
import {deployF1600_170} from "./ZZZ_FastKeccak170.sol";
import {ZZZ_E2ERef, E2E_PK_SIZE} from "./ZZZ_E2ERef.sol";
import {MLDSA44Verifier} from "../src/MLDSA44Verifier.sol";

contract KATMLDSA44Test is Test {
    /// one fixture shard (ABI tuple emitted by kat_build.py; field order
    /// matches SHARD_T there — abi.decode is positional)
    struct Shard {
        bytes[] pkBlobs; // deduplicated 20,544-byte pk payloads
        uint256[] pkIdx; // case -> pk index
        bytes[] msgs;
        bytes[] sigs;
        bool[] expect; //   oracle-reproduced verdict (empty ctx)
        string[] labels;
    }

    /// in-repo shard builder (see tools/fixtures/README_shards.md); vm.ffi
    /// runs with cwd = the repository root, so the path is repo-relative.
    string constant FX = "tools/fixtures/kat_build.py";

    ZZZ_E2ERef refVerifier;
    MLDSA44Verifier shipped;
    uint256 private _pkNonce;

    function setUp() public {
        vm.etch(_F1600_AT, _F1600_CODE);
        refVerifier = new ZZZ_E2ERef();
        shipped = new MLDSA44Verifier(deployF1600_170());
    }

    // ------------------------------------------------------------------ utils

    function _read(string memory name) internal returns (bytes memory out) {
        string[] memory c = new string[](3);
        c[0] = "pythonref/myenv/bin/python";
        c[1] = FX;
        c[2] = name;
        out = vm.ffi(c);
        require(out.length > 64, "empty fixture shard");
    }

    /// Place a raw pk payload as account code (code == blob, no prefix), which
    /// is what the reference verifier's EXTCODECOPY stream expects. vm.etch
    /// rather than CREATE, because the raw payload starts with tr = H(pk,64)
    /// and ~1/256 of keys therefore yield a blob EIP-3541 forbids deploying
    /// (reproduced with an official ACVP key in test/ACVP_MLDSA44.t.sol).
    function _placeRefPk(bytes memory blob) internal returns (address a) {
        a = address(uint160(uint256(keccak256(abi.encodePacked("kat.pk.slot", ++_pkNonce)))));
        vm.etch(a, blob);
    }

    function _deployData(bytes memory data) internal returns (address ptr) {
        bytes memory initCode = abi.encodePacked(
            bytes1(0x61), uint16(data.length), hex"600e600039", bytes1(0x61), uint16(data.length), hex"6000f3", data
        );
        assembly ("memory-safe") {
            ptr := create(0, add(initCode, 32), mload(initCode))
        }
        require(ptr != address(0), "pk data contract deploy failed");
    }

    /// The shipped verifier's pk data contract: 0x00 || payload (20,545 bytes).
    function _deployShippedPk(bytes memory blob) internal returns (address) {
        return _deployData(bytes.concat(hex"00", blob));
    }

    /// reference verifier, revert-tolerant: accepted == (call ok && true)
    function _acceptRef(address pk, bytes memory m, bytes memory sig) internal view returns (bool accepted) {
        (bool ok, bytes memory ret) =
            address(refVerifier).staticcall(abi.encodeCall(ZZZ_E2ERef.verify, (pk, m, sig)));
        accepted = ok && ret.length == 32 && abi.decode(ret, (bool));
    }

    /// shipped verifier, revert-tolerant
    function _acceptShipped(address pk, bytes memory m, bytes memory sig) internal view returns (bool accepted) {
        (bool ok, bytes memory ret) =
            address(shipped).staticcall(abi.encodeCall(MLDSA44Verifier.verify, (pk, m, sig)));
        accepted = ok && ret.length == 32 && abi.decode(ret, (bool));
    }

    // ------------------------------------------------------------ shard runner

    /// Every case of the shard is fed to BOTH verifiers; any divergence from
    /// the oracle verdict — or between the two implementations — fails.
    function _runShard(uint256 k) internal {
        Shard memory s = abi.decode(_read(string.concat("kat_", vm.toString(k), ".hex")), (Shard));

        address[] memory refPk = new address[](s.pkBlobs.length);
        address[] memory shipPk = new address[](s.pkBlobs.length);
        for (uint256 i = 0; i < s.pkBlobs.length; ++i) {
            assertEq(s.pkBlobs[i].length, E2E_PK_SIZE, "pk blob size");
            refPk[i] = _placeRefPk(s.pkBlobs[i]);
            shipPk[i] = _deployShippedPk(s.pkBlobs[i]);
        }

        // Every case in this family is a MUST-ACCEPT on its own key, so the
        // shard is also a statement that the pk blobs are pairwise distinct
        // and correctly expanded: a shard whose keys collapsed to one would
        // fail on the first case whose signature was made under another key.
        assertEq(s.pkBlobs.length, s.sigs.length, "one distinct key per case");

        for (uint256 i = 0; i < s.sigs.length; ++i) {
            assertTrue(s.expect[i], "the KAT family is must-accept only");
            _assertBothAccept(refPk[s.pkIdx[i]], shipPk[s.pkIdx[i]], s.msgs[i], s.sigs[i], s.labels[i], k, i);
        }
        console.log("KAT shard, cases / distinct keys / must-accept:", s.sigs.length, s.pkBlobs.length, s.sigs.length);
    }

    /// One case, in its own frame: the shard loop is otherwise deep enough to
    /// exhaust the Yul stack scheduler at `optimizer_runs = 10000`.
    function _assertBothAccept(
        address refPk,
        address shipPk,
        bytes memory m,
        bytes memory sig,
        string memory label,
        uint256 k,
        uint256 i
    ) internal view {
        bool gotRef = _acceptRef(refPk, m, sig);
        bool gotShip = _acceptShipped(shipPk, m, sig);
        if (!gotRef || !gotShip) {
            console.log("KAT MISMATCH shard/case:", k, i);
            console.log("  label:", label);
            console.log("  reference / shipped:", gotRef, gotShip);
        }
        assertTrue(gotRef, label);
        assertTrue(gotShip, label);
    }

    function test_kat_shard0() public {
        _runShard(0);
    }

    function test_kat_shard1() public {
        _runShard(1);
    }

    function test_kat_shard2() public {
        _runShard(2);
    }

    function test_kat_shard3() public {
        _runShard(3);
    }
}
