#!/usr/bin/env python3
"""
kat_build.py — fixture-shard builder for test/KAT_MLDSA44.t.sol.

  usage (this is what vm.ffi runs, cwd = repository root):
      pythonref/myenv/bin/python tools/fixtures/kat_build.py kat_0.hex
      pythonref/myenv/bin/python tools/fixtures/kat_build.py --build   # all

OUTPUT — hex text (no 0x, no newline) on stdout; the shards are cached under
test/fixtures/ and rebuilt only when missing.

  kat_0.hex .. kat_3.hex   Shard = (bytes[] pkBlobs, uint256[] pkIdx,
                                    bytes[] msgs, bytes[] sigs,
                                    bool[] expect, string[] labels)
                           — the same tuple shape acvp_build.py emits, so the
                           two suites share a decoder shape.

CORPUS — all 100 records of pythonref/assets/PQCsignKAT_Dilithium2.rsp, on
**100 distinct keys**, every one a MUST-ACCEPT.  Exactly ONE of those 100 is
used anywhere else in the tree (count 0, and only for its `mlen` field, in
vecgen.py), so these shards are the only consumer of the other 99 keys.

WHAT THIS CORPUS IS, AND WHAT IT IS NOT — read this before citing it.

  * It is NOT a NIST artefact and carries no NIST authority.  The file is in
    the NIST PQC KAT ("PQCsignKAT") *format* and its seeds and messages are the
    ones the NIST KAT harness produces — `AES256_CTR_DRBG(bytes(range(48)))`,
    48-byte seed then `mlen` message bytes per record, which this builder
    REPLAYS and asserts byte-for-byte.  The keys and signatures, however, were
    generated by `pythonref/dilithium_py` under FIPS 204 ML-DSA-44.  The
    upstream `dilithium-py` file of the same name holds NIST PQC Round 3
    Dilithium2 vectors and does not match this one.
  * What it therefore buys is BREADTH, not authority: 100 independent keys and
    100 independent messages of 33 bytes, signed by a third-party Python
    implementation and verified by both EVM verifiers.  It is a differential
    check against `dilithium_py` at scale, in the same class as the `fs_*`
    fuzz battery, and it is NOT evidence that NIST accepts these signatures.
    The official-answer coverage lives in `ah_*` / `at_*` / `kg_acvp_*`.

VERDICTS are never invented.  For every record this builder
  (i)   replays the KAT DRBG and asserts the file's `seed` and `msg` are the
        bytes it produces (so a doctored record is a build failure);
  (ii)  asserts `smlen == mlen + 2420` and that `sm` is `signature ‖ message`;
  (iii) asserts the pythonref oracle accepts (pk, msg, sig) as pure ML-DSA-44
        with an EMPTY context — which is the interface both EVM verifiers
        implement — before emitting `expect = true`;
  (iv)  asserts the 100 public keys are pairwise distinct, and that none of
        them occurs in the ACVP corpora, so this family is breadth and not a
        second copy of something already tested.
Any failure aborts the build.

SHARDING is round-robin (case i -> shard i % 4): 25 cases each.

REGENERATE:
  pythonref/myenv/bin/python tools/fixtures/kat_build.py --build
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import fx_common as F  # noqa: E402

NAMES = [f"kat_{k}.hex" for k in range(4)]
N_SHARDS = 4
SHARD_T = "(bytes[],uint256[],bytes[],bytes[],bool[],string[])"

KAT_FILE = F.PYTHONREF / "assets" / "PQCsignKAT_Dilithium2.rsp"
# The NIST KAT harness's fixed DRBG entropy input.
KAT_DRBG_SEED = bytes(range(48))
N_RECORDS = 100


def _records():
    """Every `count = k` block of the .rsp, as a dict of its 8 fields."""
    blocks = [b for b in KAT_FILE.read_text().split("\n\n")[1:] if b.strip()]
    out = []
    for b in blocks:
        f = dict(line.split(" = ", 1) for line in b.strip().split("\n"))
        missing = {"count", "seed", "mlen", "msg", "pk", "sk", "smlen", "sm"} - set(f)
        if missing:
            raise SystemExit(f"kat_build: record {len(out)} is missing {sorted(missing)}")
        out.append(f)
    return out


class Case:
    __slots__ = ("pk", "msg", "sig", "exp", "label")

    def __init__(self, pk, msg, sig, exp, label):
        self.pk, self.msg, self.sig = pk, msg, sig
        self.exp, self.label = exp, label


def build_corpus():
    from dilithium_py.drbg.aes256_ctr_drbg import AES256_CTR_DRBG

    recs = _records()
    if len(recs) != N_RECORDS:
        raise SystemExit(f"kat_build: {len(recs)} records, expected {N_RECORDS}")

    def check(cond, what):
        if not cond:
            raise SystemExit(f"kat_build: {what}")

    drbg = AES256_CTR_DRBG(KAT_DRBG_SEED)
    cases, pks = [], set()
    for i, f in enumerate(recs):
        check(int(f["count"]) == i, f"record {i}: count = {f['count']}")
        mlen, smlen = int(f["mlen"]), int(f["smlen"])
        # (i) the KAT DRBG stream, replayed
        seed = drbg.random_bytes(48)
        msg = drbg.random_bytes(mlen)
        check(bytes.fromhex(f["seed"]) == seed,
              f"record {i}: `seed` is not the KAT DRBG's 48 bytes")
        check(bytes.fromhex(f["msg"]) == msg,
              f"record {i}: `msg` is not the KAT DRBG's {mlen} bytes")
        # (ii) the signed-message envelope
        pk, sm = bytes.fromhex(f["pk"]), bytes.fromhex(f["sm"])
        check(smlen == mlen + F.SIG_LEN, f"record {i}: smlen != mlen + {F.SIG_LEN}")
        check(len(sm) == smlen, f"record {i}: len(sm) != smlen")
        sig, tail = sm[:F.SIG_LEN], sm[F.SIG_LEN:]
        check(tail == msg, f"record {i}: sm does not end in msg")
        check(len(pk) == F.PK_LEN, f"record {i}: len(pk) = {len(pk)}")
        # (iii) the oracle accepts, at the interface the EVM verifiers implement
        check(F.verify_pure(pk, msg, sig, b""),
              f"record {i}: oracle REJECTS the KAT signature at empty ctx — this "
              f"corpus is not FIPS 204 ML-DSA-44 and must not be emitted as "
              f"must-accept")
        pks.add(pk)
        cases.append(Case(pk, msg, sig, True, f"KAT{i}"))

    # (iv) breadth, asserted
    check(len(pks) == N_RECORDS,
          f"only {len(pks)} distinct public keys among {N_RECORDS} records")
    ml, _ = F.acvp_data()
    acvp_pks = {t["pk"] for bucket in ("sigVer", "sigGen", "tr1")
                for k in ("pure", "preHash") for t in ml[bucket][k]}
    overlap = {p.hex().upper() for p in pks} & {p.upper() for p in acvp_pks}
    check(not overlap,
          f"{len(overlap)} KAT key(s) also appear in the ACVP corpora; this "
          f"family is meant to be an independent key population")
    return cases


def build_all():
    cases = build_corpus()
    pk_cache = {c.pk: F.pk_blob(c.pk) for c in cases}
    for k, idxs in enumerate(F.round_robin(len(cases), N_SHARDS)):
        blobs, order, pkidx = [], {}, []
        for i in idxs:
            pk = cases[i].pk
            if pk not in order:
                order[pk] = len(blobs)
                blobs.append(pk_cache[pk])
            pkidx.append(order[pk])
        shard = (
            blobs,
            pkidx,
            [cases[i].msg for i in idxs],
            [cases[i].sig for i in idxs],
            [cases[i].exp for i in idxs],
            [cases[i].label for i in idxs],
        )
        F.write_shard(f"kat_{k}.hex", F.enc(SHARD_T, shard))


if __name__ == "__main__":
    F.main(sys.argv, build_all, NAMES)
